// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ChatRepoUtil$ReasonableChatServer = require("./ChatRepoUtil.bs.js");

var initialChatState = /* record */[
  /* users : [] */0,
  /* messages : [] */0
];

var chatState = /* record */[/* contents */initialChatState];

function getOrCreateUser(name) {
  var match = ChatRepoUtil$ReasonableChatServer.getOrCreateUser(name, chatState[/* contents */0][/* users */0]);
  var init = chatState[/* contents */0];
  chatState[0] = /* record */[
    /* users */match[1],
    /* messages */init[/* messages */1]
  ];
  return match[0];
}

function setUserAvailability(isAvailable, id) {
  var init = chatState[/* contents */0];
  chatState[0] = /* record */[
    /* users */ChatRepoUtil$ReasonableChatServer.changeUserAvailability(isAvailable, id, chatState[/* contents */0][/* users */0]),
    /* messages */init[/* messages */1]
  ];
  return /* () */0;
}

function addMessage(text, senderId) {
  var match = ChatRepoUtil$ReasonableChatServer.addMessage(text, senderId, chatState[/* contents */0][/* messages */1]);
  var init = chatState[/* contents */0];
  chatState[0] = /* record */[
    /* users */init[/* users */0],
    /* messages */match[1]
  ];
  return match[0];
}

function getState(param) {
  return chatState[/* contents */0];
}

function resetState(param) {
  chatState[0] = initialChatState;
  return initialChatState;
}

exports.getOrCreateUser = getOrCreateUser;
exports.setUserAvailability = setUserAvailability;
exports.addMessage = addMessage;
exports.getState = getState;
exports.resetState = resetState;
/* No side effect */
