// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var SocketIO$ReasonableChatServer = require("./SocketIO.bs.js");
var ChatRepository$ReasonableChatServer = require("./ChatRepository.bs.js");
var ClientCommandProcessor$ReasonableChatServer = require("./ClientCommandProcessor.bs.js");

function addDummyData(param) {
  var dummyUser = ChatRepository$ReasonableChatServer.getOrCreateUser("Dummy user");
  ChatRepository$ReasonableChatServer.addMessage("Are you talking to me?", dummyUser[/* id */0]);
  ChatRepository$ReasonableChatServer.addMessage("Well I'm the only one here.", dummyUser[/* id */0]);
  return ChatRepository$ReasonableChatServer.setUserAvailability(false, dummyUser[/* id */0]);
}

addDummyData(/* () */0);

console.log("Starting the server...");

SocketIO$ReasonableChatServer.startServer((function (authenticationState, clientCommand, broadcast, send) {
        var match = ClientCommandProcessor$ReasonableChatServer.processClientCommand(authenticationState, clientCommand);
        Belt_Option.map(match[1], broadcast);
        Belt_Option.map(match[2], send);
        return match[0];
      }));

exports.addDummyData = addDummyData;
/*  Not a pure module */
