// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ChatRepository$ReasonableChatServer = require("./ChatRepository.bs.js");

function addDummyData(param) {
  var dummyUser = ChatRepository$ReasonableChatServer.getOrCreateUser("Dummy user");
  ChatRepository$ReasonableChatServer.addMessage("Are you talking to me?", dummyUser[/* id */0]);
  ChatRepository$ReasonableChatServer.addMessage("Well I'm the only one here.", dummyUser[/* id */0]);
  return ChatRepository$ReasonableChatServer.setUserAvailability(false, dummyUser[/* id */0]);
}

addDummyData(/* () */0);

exports.addDummyData = addDummyData;
/*  Not a pure module */
