// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");

function encodeMessage(message) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "id",
                message[/* id */0]
              ],
              /* :: */[
                /* tuple */[
                  "senderId",
                  message[/* senderId */2]
                ],
                /* :: */[
                  /* tuple */[
                    "text",
                    message[/* text */3]
                  ],
                  /* :: */[
                    /* tuple */[
                      "creationDate",
                      new Date(message[/* creationDate */1]).toISOString()
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

function encodeUser(user) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "id",
                user[/* id */0]
              ],
              /* :: */[
                /* tuple */[
                  "name",
                  user[/* name */1]
                ],
                /* :: */[
                  /* tuple */[
                    "avatarUrl",
                    Json_encode.nullable((function (prim) {
                            return prim;
                          }), user[/* avatarUrl */2])
                  ],
                  /* :: */[
                    /* tuple */[
                      "isAvailable",
                      user[/* isAvailable */3]
                    ],
                    /* :: */[
                      /* tuple */[
                        "isTyping",
                        user[/* isTyping */4]
                      ],
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

function encodeChatState(chatState) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "users",
                Json_encode.list(encodeUser, chatState[/* users */0])
              ],
              /* :: */[
                /* tuple */[
                  "messages",
                  Json_encode.list(encodeMessage, chatState[/* messages */1])
                ],
                /* [] */0
              ]
            ]);
}

exports.encodeMessage = encodeMessage;
exports.encodeUser = encodeUser;
exports.encodeChatState = encodeChatState;
/* Json_encode Not a pure module */
